### ISSUE TITLE
Adding "stripeAccount" param for direct charges fails the transaction

### ISSUE THREAD

**Issue by yosefsun** [stripe/stripe-terminal-ios#10]
When I try to create a direct charge on behalf of a connected (stripe connect) account, I recieve an error.

I added to the paymentParams the following param (after initialization of the params with amount and currency) :

> paymentParams.stripeAccount = "[some_stripe_connect_acct_id]"

I recieve :

> Confirm PaymentIntent Failed
>  No such paymentIntent: [some_payment_intent_id]

* btw, destination charges for the same account are working

screenshots :

<img width="492" alt="screen shot 2018-10-30 at 10 50 50 pm" src="https://user-images.githubusercontent.com/5140364/47763299-7b802180-dc96-11e8-9a00-0d94b48b1706.png">
<img width="492" alt="screen shot 2018-10-30 at 10 51 08 pm" src="https://user-images.githubusercontent.com/5140364/47763300-7b802180-dc96-11e8-9f9a-c5e83768210b.png">

**Comment by bg-stripe** [comment]
Hey @yosefsun ,

Thanks for reporting this issue. I think you've indeed found a bug – we'll be sure to get a fix into the next SDK release (~1-2 weeks from now).

I'll update the issue when the fix is out!

**Comment by bg-stripe** [comment]
Following up – just had a chance to look into this a bit more closely. The issue here is actually that you'll need to set a `Stripe-Account` header when creating the connection token on your backend. 

Previously, this wasn't supported in the example app's `BackendSimulator`, so I've updated the example app in #12 to support passing a `stripeAccount` when creating a connection token. If you want to try this out in the example now, you would set your `stripeAccount` here:

https://github.com/stripe/stripe-terminal-ios/blob/3a0e7cc9f3a0c3d58689ee50ae5a3eceed0908a2/Example/Example/APIClient.swift#L22

Note that in your own app, you should _not_ create the connection token or capture the PaymentIntent client-side (we do this in the example app for demonstration purposes only). Be sure to create the connection token by [setting up an endpoint on your backend](https://stripe.com/docs/terminal/ios#connection-token).

Let me know if you have any additional questions!

**Comment by crawler** [comment]
What if Terminal should process both, direct charges tho the connected account, and the charges to the platform account, that being split later with the Transfers? If i create connection token to the platform account, then the terminal can't see payment intent that i created for the destination charge with connected account id. If the connection token is created for the connected account, then the Terminal can't see payment intents created for the platform account.

**Comment by jil-stripe** [comment]
Hi @crawler!
To process for different accounts (including connected & platform accounts) using the same reader, you'll need to [disconnect and reconnect the reader](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)clearCachedCredentials) to switch from one to the other.

Could you tell us a little bit more about how you're using Terminal, either here or by emailing `support-terminal@stripe.com`? We might be able to give you more specific advice if we have more information about what you're trying to do.
