### ISSUE TITLE
Capturing payment intents twice

### ISSUE THREAD

**Issue by chinedufn** [stripe/stripe-terminal-ios#100]
Hey! I'm very new to Swift, so apologies if I say anything that's nooby.

## Summary

I had an issue where a customer was charged the wrong amount.

I was confused for a bit, then finally nailed it down to what seems like a bit of a foot gun.

If you `Terminal.shared.collectPaymentMethod` but then don't actually provide the card.

Then you come back later and `Terminal.shared.collectPaymentMethod` again and provide a card, the callback for the first `collectPaymentMethod` call will be called.

I eventually realized that you're supposed to use the `Cancelable` that `collectPaymentIntent` returns to cancel the first request if you want to prevent this.

## Potential Path Forwards

As far as I can tell, if you trigger a payment method collection and then insert the credit card, you will always expect to be charged for the payment intent that you just provided. I can't currently think of a reason where you'd want a previous `collectPaymentIntent` callback to fire when the card was provided.

So, to me it seems like this confusing scenario can be prevented by just automatically cancelling an in-flight `collectPaymentIntent` if you call the message again.

I'm too new to Swift to know what the idiomatic way to do this might be, but perhaps by storing `Terminal.shared.mostRecentCollectCancelable = Cancelable?` and then just automatically calling that `Cancelable` (if it is non null) whenever `collectPaymentIntent` is called.

## SDK version

1.4.0

---

Thanks!

**Comment by bric-stripe** [comment]
👋 @chinedufn The Terminal SDK only supports one command at a time and does rely on commands being explicitly canceled. If the first `collectPaymentIntent` hasn't been canceled or provided with a payment or timed out, the second call to `collectPaymentIntent` _should_ be failing quickly with an error provided to its completion block of, `SCPErrorBusy` with a message "Could not execute collectPaymentIntent because the SDK is busy with another command: collectPaymentIntent", and return a nil cancelable to that second call.

Could you confirm the second collect calls are indeed getting this error? That error would then explain why a then provided payment got attributed to that first collect call which is still the running command.

If the second collect call _is_ returning a cancelable and _no_ error, could you provide some more information to help us reproduce and debug? I tried with 1.4.0 SDK and both a chipper and the P400 but both were acting as expected where the second calls failed with busy.

> perhaps by storing Terminal.shared.mostRecentCollectCancelable = Cancelable? and then just automatically calling that Cancelable

yeah, this would work well for the situation you hit but for now the SDK doesn't have much implicit auto cancel or anything and has leaned more towards explicit actions. Something we'll keep in mind though. But I do think that same auto cancel logic should be doable to have in your app's code.

**Comment by chinedufn** [comment]
@bric-stripe ah, thanks! Your description of what happened explains everything so disregard how I _thought_ it played out.

---

Yeah for now I'm just implementing the cancellation myself.

---

Ah, I hear you on your reasoning / thought process. 

I think me saying "auto cancel" might have made it come off as being too magical.

I think what I really mean is that:

1. Right now a noobie who's just trying to quickly collect some payments and/or is new to iOS might not understand how to use the API properly (huh, of course that isn't me)

2. Said noobie should be protected from their noobiness, as long as it doesn't hurt the API experience for non-noobs.

3. I am proof that a noob can accidentally allow the wrong thing to get paid for.

4. My code mistake could have been prevented by either cancelling all old collects when collect is called, cancelling all collects (including the new one), or maybe some other better design.

5. So, yeah, I just care about not having someone else make the same silly mistake that I did. Regardless of how it's implemented.

---

That being said - I think you would have a much better sense of what is best here than I do at this time - so this is just me sharing my experience as feedback.

Thanks a lot for the library. I'm all set and you've solved my problem so I'll close this out.

Thanks!!

**Comment by bric-stripe** [comment]
this is great feedback for us to consider 👍 thanks for the clear explanation and all
