### ISSUE TITLE
On discover didUpdateDiscoveredReaders is not called

### ISSUE THREAD

**Issue by hanumanAbacus** [stripe/stripe-terminal-ios#104]
## Summary
Frequent disconnection and reconnection by manually turning of and on the terminal, doest call back didUpdateDiscoveredReaders on called discoverReaders, even when terminal is powered on

## Code to reproduce
// discovery logic
    SCPDiscoveryConfiguration *discoveryConfiguration = [[SCPDiscoveryConfiguration alloc] initWithDiscoveryMethod:SCPDiscoveryMethodBluetoothScan simulated:NO];
[SCPTerminal.shared discoverReaders:discoveryConfiguration
                                                         delegate:self
                                                       completion:^(NSError * _Nullable error) {}
// delegate not getting called
- (void)terminal:(SCPTerminal *)terminal didUpdateDiscoveredReaders:(NSArray<SCPReader *> *)readers { }

// when disconnected, I get a call back below. in which case I call discoverReaders method
- (void)terminal:(SCPTerminal *)terminal didReportUnexpectedReaderDisconnect:(nonnull SCPReader *)reader {

## iOS version
ios14

## Installation method
pod

## SDK version
2.0.1

**Comment by bric-stripe** [comment]
hi, thanks for the report. Just want to confirm I'm reproducing the same thing. Steps I'm using:

1. start discovery with no readers turned on
2. turn on a reader, see it be reported in `didUpdateDIscoveredReaders`
3. Issue: turn off the reader, see there's no update about it being turned off. so most recent discovered readers is still as previously reported
4. Issue: turn the reader back on, see there's no update about it being turned on because technically the reader was still reported as discovered

is that what you're seeing? if so I'll investigate fixing that up. or do you have a scenario where `didUpdateDiscoveredReaders` reports _no_ readers even though the reader is on? 

if you're seeing something other than what I outlined above please add additional steps to reproduce and logs from the Terminal.setLogListener would be great.

**Comment by hanumanAbacus** [comment]
@bren-stripe 
After disconnection called on didReportUnexpectedReaderDisconnect, I call SCPCancelable on  current discoverReaders
and reinitiate discoverReaders. 
In which case the  didUpdateDIscoveredReaders is not called if turned back the terminal on.

**Comment by hanumanAbacus** [comment]
@bric-stripe do you have an update for me

**Comment by bric-stripe** [comment]
@hanumanAbacus I just tried reproducing again and haven't fully seen what I believe you're reporting so don't have any great updates. Can you confirm you're using a Chipper 2X as the reader when you're hitting this problem? Could you also provide logs that get reported via the `Terminal.logListener` after the unexpected disconnect? Or if you have a simple sample code you could provide that would be great too.

The behavior I'm seeing with a Chipper 2X is when I start a `discoverReaders` in the unexpected disconnect callback the reader that was just turned of gets reported immediately[0] and so when the reader then gets turned on it's not a change in discovered readers so it doesn't then get reported. But it sounds like you're saying you never see the reader get reported to the provided delegate? 

[0] the fact that it gets reported right away is a bug that I'll be investigating but may take some time as I believe the issue is in a dependency we have for the bluetooth readers...and my concern is this doesn't sound like exactly what you're reporting so I'm not confident fixing that will help with your case.

**Comment by allendav** [comment]
I believe I am seeing this as well with SDK 1. Haven't tried it with SDK 2 yet. Here's my steps which mirror y'alls

- After calling `Terminal.shared.discoverReaders` I receive my reader (BBPOS Chipper 2X BT) in `didUpdateDiscoveredReaders`
- I purposely power off that that reader (holding down the power button for 5+ sec)
- I notice I do not get `didReportUnexpectedReaderDisconnect`
- I attempt `Terminal.shared.connectReader` on that reader
- After about 10 seconds, that fails
- If I turn that reader on again at this point, I do NOT get `didUpdateDiscoveredReaders`
- If I turn a second reader on at this point (in addition to the first), I get both readers in `didUpdateDiscoveredReaders` and I am able to successfully connect to either

**Comment by bric-stripe** [comment]
thanks @allendav, I can reproduce that behavior and we're working on a fix with BBPOS for the missing update when turning the last reader off/back on, but not sure yet on any timing. Note since the reader wasn't connected to you shouldn't expect an unexpected reader disconnect, but you should get a `didUpdateDiscoveredReaders` with an empty set (that's what the fix would be for this)

**Comment by allendav** [comment]
> we're working on a fix with BBPOS for the missing update when turning the last reader off/back on, but not sure yet on any timing

Thank you! Looking forward to trying it out when it is ready. I assume the fix would be for SDK 2 only?

**Comment by bric-stripe** [comment]
> I assume the fix would be for SDK 2 only?
sorry for delay responding, that's correct. We should have this fixed up in our October release which is planned to be out ~Oct 18th
