### ISSUE TITLE
SDK stays stuck in discoverReaders

### ISSUE THREAD

**Issue by thomaskellough** [stripe/stripe-terminal-ios#106]
## Summary
I'm having an issue where once the SDK calls discover readers, it stays in that mode and doesn't cancel out. This causes problems because if I leave a screen and come back to it, my tableview won't show which readers are discovered because there is nothing to update.

Right now, I'm saving the readers in a static property of a singleton class, but I don't think that's the best method. 

Is there a way to cancel the discover reader process? In another part of my app I'm trying to take payments via no terminal, but I get the same error that the SDK cannot do anything because it's busy with discoverReader status.

## Code to reproduce
```
func discoverReadersAction() {
        self.discoverCancelable = nil
        if self.terminal == nil {
            self.terminal = Terminal.shared
            self.terminal?.simulatorConfiguration.availableReaderUpdate = .none
        }

        if let connectedReader = self.terminal?.connectedReader {
            attemptToConnectToBluetoothReader(connectedReader)
        } else {
            self.discoverCancelable = terminal?.discoverReaders(discoveryConfig, delegate: self) { error in
                if let error = error {
                    log.error("discoverReaders failed: \(error)")
                    self.customStripeCardReaderDelegate?.notifyAlreadyDiscovering()
                } else {
                    log.info("discoverReaders succeeded")
                }
            }
        }
        
    }
```

And here is the error code from my logs.
`
Error 08/13/2021 08:21:19 - StripeCardReaderManager.swift - discoverReadersAction() - Line: 83 - discoverReaders failed: Error Domain=com.stripe-terminal Code=1000 "Could not execute discoverReaders because the SDK is busy with another command: discoverReaders." UserInfo={NSLocalizedDescription=Could not execute discoverReaders because the SDK is busy with another command: discoverReaders., com.stripe-terminal:Message=Could not execute discoverReaders because the SDK is busy with another command: discoverReaders.}
`

## iOS version
iOS 14.5

## Installation method
Cocoapods
## SDK version
StripeTerminal (2.0.1)

**Comment by bric-stripe** [comment]
👋 hello, I _suspect_ the confusion here may be that even though you nil'd the cancelable on that first line in the method, that doesn't cancel our [`SCPCancelable`s](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPCancelable.html#/c:objc(cs)SCPCancelable(im)cancel:). You have to explicitly call `cancel` on the cancelable to cancel the discovery. And that cancel is an async operation with a completion block (since there is some async cleanup needed inside the SDK and some operations have a point where they can no longer be canceled). Before you attempt another discover you'd ideally make sure your first discover calls completion block has run since that's when we've confidently completed the previous discovery (either by connecting to a reader or from a canceled discovery).

**Comment by thomaskellough** [comment]
@bric-stripe Thank you so much for your answer. That is interesting to me, I would have thought there would have been some kind of cascade effect to cancel anything going on once you set the cancelable to nil. Nonetheless, I was able to work out my problem based on your suggestion. Thanks again!
