### ISSUE TITLE
Crash on trying to collectPaymentMethod with low battery

### ISSUE THREAD

**Issue by robertsammons** [stripe/stripe-terminal-ios#124]
## Summary
We are encountering a crash on several of our readers when trying to call the collectPaymentMethod with a low battery. We get a crash trace back that mentions "reportLowBatteryWarning"

## Code to reproduce
Code is in production, can provide privately if need be

## iOS version
iOS 15.1

## Installation method
Stripe Package Manager

## SDK version

Based on logs we believe this started with 2.3.0 but are on the latest 2.4.0

## Other information

Attached crash trace from Xcode.

<img width="577" alt="Screen Shot 2021-11-24 at 9 37 18 am" src="https://user-images.githubusercontent.com/7057395/143213659-6a2c7a08-5c76-4394-9a65-3e447edcb447.png">

I'm not sure if this is a required method to support but it isn't mentioned as a required method?

**Comment by robertsammons** [comment]
<img width="472" alt="Screen Shot 2021-11-24 at 10 04 08 am" src="https://user-images.githubusercontent.com/7057395/143217453-3260ed14-7513-4ae9-b9bd-52a1f2b584e0.png">

**Comment by robertsammons** [comment]
@bric-stripe Thanks for the reply, unfortunately the work around is likely a lot of work from my side, just the way I've built it means I have a connect readers screen that has the delegate reference then obviously disappears as it closes. I'll definitely consider changing this in the future as the additional methods like low battery would be useful to know.

One question I have is we're not sure if this was introduced in V2.3.0 or if it has always been there,  just thinking of reverting back to an older version if the bug was introduced with this version. It may have just matched up to their being more readers from our side in use around the same time frame but worth an ask.

**Comment by bric-stripe** [comment]
> One question I have is we're not sure if this was introduced in V2.3.0 or if it has always been there

I checked our git blame and the problem has been there since the first 2.0.0 release 😞 

> unfortunately the work around is likely a lot of work from my side

There may be some not terribly elegant, but not overly complicated, options/band aids here for a short term solution. In our Example code we have a `DelegateAnnouncer` that we use that provides a long lived singleton that you may be able to make use of or something similar: 
* announcer: https://github.com/stripe/stripe-terminal-ios/blob/c1ff95a18e22a96cca5d21a7d20ced9d546ff3f5/Example/Example/DelegateAnnouncer.swift#L71
* usage https://github.com/stripe/stripe-terminal-ios/blob/c1ff95a18e22a96cca5d21a7d20ced9d546ff3f5/Example/Example/ReaderDiscoveryViewController.swift#L146
* and then anything that does need to receive the delegate callbacks adds itself as a listener: https://github.com/stripe/stripe-terminal-ios/blob/c1ff95a18e22a96cca5d21a7d20ced9d546ff3f5/Example/Example/ReaderDiscoveryViewController.swift#L44

if you don't need the added multiple listener support that can probably be simplified a good bit.

**Comment by robertsammons** [comment]
Perfect, thanks for that. You're right I think that'll do the job for now without too much work.

**Comment by robertsammons** [comment]
Thanks for solving this one!
