### ISSUE TITLE
discoverReaders: completion is never called when connectionToken is unavailable

### ISSUE THREAD

**Issue by agordeev** [stripe/stripe-terminal-ios#128]
stripe terminal for iOS version 2.0.4

I'm following steps from this guide: https://stripe.com/docs/terminal/payments/connect-reader

The problem is that the completion block is never called if the backend is unreachable and unable to return the connection token.
Here's my code.

```swift
class ReaderDiscoveryService: NSObject {
    var discoverCancelable: Cancelable?

    // Action for a "Discover Readers" button
    func discoverReaders() {
        let config = DiscoveryConfiguration(
          discoveryMethod: .bluetoothScan,
          simulated: true
        )

        self.discoverCancelable = Terminal.shared.discoverReaders(config, delegate: self) { error in
            print("This message won't print if the backend is unreachable")
        }
    }
}
```

**Comment by jil-stripe** [comment]
Hi @agordeev!

I don't think this is a bug. We're unable to look at your ConnectionTokenProvider and see if a network request has failed or not, so we require that your code tell us if there was an error fetching the connection token. 

The `fetchConnectionToken` method takes a completion handler that should be called with an error if you want the Terminal SDK to know there was a connection token issue. If you want to enforce a timeout or immediately error if the internet is unavailable, you can do that in the `fetchConnectionToken` method that you implement.

For example, to write a Connection Token provider that fails immediately when your reachability object says the internet is unreachable _or_ fails after Alamofire has failed to make a successful request to your backend, you might write:

```swift
class APIClient: ConnectionTokenProvider {
    func fetchConnectionToken(_ completion: @escaping ConnectionTokenCompletionBlock) {

        // If the device is offline, call completion immediately
        if(!yourReachabilityObject.isReachable) {
            completion(nil, NSError(...))
            return
        }

        // Otherwise, fetch the connection token from your backend.
        Alamofire.request("example.com")
            .validate(statusCode: 200..<300)
            .validate(contentType: ["application/json"])
            .responseData { response in
                switch response.result {
                case let .success(body):
                    let connectionToken = "..." // Extract token from response body in whatever way makes sense for you
                    completion(connectionToken, nil)
                case let .failure(error):
                    completion(nil, error)
                }
            }
    }
}
```

We're unable to tell what constitutes a failure from within your code, so we require that you call the completion with an error to indicate when a failure takes place.

**Comment by agordeev** [comment]
Thanks for the explanation. Well, that's unobvious behavior. The user expects the completion handler to be called. Either with the result or an error.

**Comment by jil-stripe** [comment]
I see! I was focused on the connection token provider, but the discoverReaders completion should be getting called in that situation. We'll aim to have that bug fixed in our January release.

**Comment by bric-stripe** [comment]
👋 I'm reviewing old issues and I believe this one is currently acting as expected still after reviewing some things, though I can understand the expectation to instead error.

Right now, `.bluetoothScan` and `.bluetoothProximity` discovery intentionally don't fail if the connection token request fails. The Bluetooth discovery process needs the connection token to fill in the location details for a Bluetooth reader. But that's currently a non-blocking part of discovery because the decision was made to focus on returning the discovered readers. So if location info request fails, `discoverReaders` will still return the discovered readers, but with nil `location` property. If you attempt to connect and the connection token provider returns an error that will of course fail. This behavior is currently consistent between the iOS and Android SDKs but I'm also raising it internally to discuss if we do want to reconsider this. Closing out this ticket but will re-open if this changes.
