### ISSUE TITLE
SCPTerminal processPayment PIN error on simulated reader

### ISSUE THREAD

**Issue by chrishmpolis** [stripe/stripe-terminal-ios#135]
## Summary
Running on iOS Simulator using simulated Chipper BBPOS (`CHB20Simulator2`). Making a `processPayment` request the Terminal responds with an error message stating that the maximum allowable number of PIN retries has been exceeded.

## Code to reproduce
Nothing special just a request for `SCPTerminal` to `processPayment` for a `PaymentIntent`

## iOS version
15.0

## Installation method
Swift Package

## SDK version
2.5.0

## Other information

**It went away after I ran "Erase All Content And Settings" on the simulator.**  

This is what I see when printing the error in console

```(SCPProcessPaymentError?) error = 0x0000600000071c80 {
  baseNSError@0 = domain: "com.stripe-terminal" - code: 6000 {
    _userInfo = 0x0000600001578e20
  }
  _paymentIntent = Failed to get the 'some' field from optional '_paymentIntent'
  _requestError = 0x0000600001b56550
  _declineCode = 0x0000600001b2ff30 "pin_try_exceeded"
}```

**Comment by jil-stripe** [comment]
Hi @chrishmpolis!

I think I've found the failing request - if you could confirm that the failing PaymentIntent has an ID of `pi_3KMaGtCXl2cS0UTV0MP6wPCw`, that would help me be sure of what's going on.

It looks like that PaymentIntent has an amount of 36.75. When payments are made with the physical test card, [that card will simulate different error scenarios if you create a payment ending in certain values](https://stripe.com/docs/terminal/references/testing#physical-test-cards). That PaymentIntent was declined with a `pin_try_exceeded` code because the amount ended in 75.

I'm still digging into the payments you made after this one, after you erased contents and settings on the simulator, to try to figure out why those were successful. For example, `pi_3KMaZ1CXl2cS0UTV1q5edcQo` is one of the payments made after that error, and it has a different amount that doesn't correspond to any of the test cents values, so it would succeed. Would that explain the behavior you saw?

Best,
James
