### ISSUE TITLE
v2 SDK automatically completes transaction before card is removed and no card removed event is being fired

### ISSUE THREAD

**Issue by mohammad-dwairii** [stripe/stripe-terminal-ios#138]
## Summary
v2 SDK automatically completes transaction before card is removed and no card removed event is being fired

## Code to reproduce
NA

## iOS version
13.3 and 15.1.1

## Installation method
using cocoapods, both versions 2.3.0 and 2.5.0 has the issue

## SDK version
2.3.0 and 2.5.0

**Comment by catriona-stripe** [comment]
@mohammad-dwairii could you provide us with which card reader this occurring with and the country for the account you are using?

**Comment by mohammad-dwairii** [comment]
> @mohammad-dwairii could you provide us with which card reader this occurring with and the country for the account you are using?

Hi @catriona-stripe we use bbpos reader and the country is USA

**Comment by bric-stripe** [comment]
👋 sorry for lack of response here. I'm reviewing and closing out old issues and I'm fairly confident the missing `card removed` event when a card is inserted has been fixed in 2.9.1+ but please re-open with some more details[0] if still running in to that. The transaction completing while the card is still in the reader is currently the intended behavior though. The last few comments in https://github.com/stripe/stripe-terminal-ios/issues/112#issuecomment-924031491 have some discussion for blocking your application until the card is removed that may help.

[0] SDK version using now and a serial number of a reader where you're still seeing the issue and rough timing would be great and we can dig deeper in to that
