### ISSUE TITLE
After sometime m2 device is getting disconnected.

### ISSUE THREAD

**Issue by AkshadaKad** [stripe/stripe-terminal-ios#152]
If device is not used for sometime of if app is minimised then m2 chipper device disconnects please can you help to prevent disconnection of device.

**Comment by richardliveraise** [comment]
I'm also getting this issue, and sometimes you can't discover the device anymore.

**Comment by ordinaryman09** [comment]
I'm also experiencing disconnect after sometime, and sometimes the reader is not discoverable anymore.

**Comment by bric-stripe** [comment]
sorry this also went without a response. The M2 and WisePad 3 will both reset after 24 hours for PCI compliance (the Chipper 2X did not have this behavior). See [this comment](https://github.com/stripe/stripe-terminal-ios/issues/120#issuecomment-1310624992) with a suggestion to use new auto reconnection to help with this situation. That issue is also about not being able to reconnect. Please provide timing and serial numbers of affected readers over there if still seeing inability to connect but my hope is this has been fixed in recent SDK and Firmware updates. I've got a long running test to an M2 going on right now with latest production SDK and firmware.
