### ISSUE TITLE
SDK have no way of receiving state change (no delegate) from smart readers like WisePos E

### ISSUE THREAD

**Issue by PawelErnestLuczak** [stripe/stripe-terminal-ios#154]
## Summary
So for BT readers we do have 
`Terminal.shared.connectBluetoothReader(reader, delegate: self, connectionConfig: config) {`

but for 'internet' readers we do have 
`Terminal.shared.connectInternetReader(reader, connectionConfig: config) {`

I guess one may have forgotten to add place for delegate here.

## Code to reproduce
It is not a bug, it is a missing feature

## iOS version
15.4 or whatever

## Installation method
manually using xcframework from the github release zip

## SDK version
2.8.0

**Comment by jil-stripe** [comment]
Hi @PawelErnestLuczak - this is intentional today. The delegate events provided by the BluetoothReaderDelegate are all in service of displaying information about the card reader in your app: information about reader software update progress, instructions to the cardholder about providing their card, or the current battery level. 

Internet readers all have a screen which displays this information, so we haven't yet prioritized adding a delegate to send that information to the mobile app while an internet reader is connected.

Given that this isn't a bug report in the SDK, I'm going to close this issue, but we'll prioritize this feature request internally and get to it when we can.

Thanks for writing in!

**Comment by PawelErnestLuczak** [comment]
Well, BT readers have screens too and are displaying instructions for the clients but anyway, thanks, we will patiently wait for the delegate.
![P_20220513_044210](https://user-images.githubusercontent.com/2144565/168201114-be62b080-0d72-4f06-a76c-071699a82822.jpg)
