### ISSUE TITLE
while building for mac catalyst no library for this platform was found

### ISSUE THREAD

**Issue by MaximGolovlev** [stripe/stripe-terminal-ios#174]
I am trying to convert my ipad app to MacOS using Mac Catalyst and getting this error from your library

Does this mean that the library does not yet support this system?

Can I somehow modify the library myself?

**Comment by bric-stripe** [comment]
Hi @MaximGolovlev 

>  Does this mean that the library does not yet support this system?

That's correct. I just re-investigated this and we still have an internal dependency that we need to sort out in order to provide MacCatalyst support.

> Can I somehow modify the library myself?

not that I'm aware of. I believe the only option would be to conditionally exclude StripeTerminal in catalyst builds. But depending on the app that may not make sense.

**Comment by xiaoshen-stripe** [comment]
Hi Thanks again for your feedback. Due to other higher-priority items on our roadmap, we do not have immediate plans to address this at this time. 
Note that recent Mac with Apple silicon chip can now run iPhone and iPad apps [0] out of the box. 

[0] https://support.apple.com/en-ca/guide/app-store/fird2c7092da/mac
