### ISSUE TITLE
BBPOS WisePOS E disconnects and unable to reconnect temporarily

### ISSUE THREAD

**Issue by auctifera-josed** [stripe/stripe-terminal-ios#181]
## Summary

We have integrated the BBPOS WisePOS E using the Terminal SDK (since we need to support countries other than the US) and it's working fine almost all the time, except that sometimes we are completely unable to connect to the reader regardless of what we try (restarting the app, the device, restart internet connection) and it starts working again all the sudden without any change in the code base.

## Code to reproduce

```swift
Terminal.shared.connectInternetReader(reader, connectionConfig: config, completion: completion)
```

## iOS version

15.5

## Installation method

cocoapods

## SDK version

2.12

## Other information

SDK Error: "Connecting to the reader over the internet timed out. Make sure your device and reader are on the same Wifi network and your reader is connected to the Wifi network."

And both the device and reader are in the same Wifi network which is working without any problems.

**Comment by bric-stripe** [comment]
Hi, can you provide logs from the [`Terminal.logListener`](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(cm)setLogListener:) when this happens? Or alternatively a serial number and rough timing (even just a day is fine) of an instance of when it occurred and we can then try to find some of the logs reported by the reader with that.

**Comment by bric-stripe** [comment]
I found logs for that reader and both the SDK and the reader seem to be able to talk to stripe.com without issue, but the network requests from the SDK to the reader itself are indeed timing out. I confirmed `SCPErrorInternetConnectTimeOut` is only ever returned if the request to the reader was an `NSURLErrorDomain` error with code `NSURLErrorTimedOut`, which unfortunately doesn't tell us much other than for reasons that are tricky to debug the network requests aren't getting through. The most common cause for this is local DNS resolution failing but this doesn't match that because it just all the sudden stops and then starts working again 🤔

does this happen regularly on a device you have access to? Have you seen this happen on multiple unrelated networks? Debugging the local network is the next step here. Some things to investigate, some may not be practical depending on when/where this is happening though:

* If you can set the iOS device's DNS server to be manually configured and point it to a public cloudflare or google DNS server it would be good to rule that out: https://support.stripe.com/questions/the-stripe-terminal-sdk-is-encountering-dns-errors-when-connecting-to-an-internet-reader (but again this doesn't exactly feel like that would be the issue but worth ruling out)
* You mentioned trying restarting the internet connection, but are you able to switch to a different network to see if that helps? Connecting both the iOS device and the reader to a phone's hotspot or similar, or if the phone is the iOS device that would also work to connect the reader to its hotspot.
* have you ever had this happen while using the iOS simulator but connecting to a real WisePOS E? If so, that probably has the best options for debugging: can you ping and traceroute to the reader's IP address without issue? You can get the IP from the reader diagnostics page or from the SCPReader instance returned in didUpdateDiscoveredReaders

**Comment by auctifera-josed** [comment]
Hi @bric-stripe it was the network, when it happened again we switched networks on both devices and it worked again, switch back again and it continues not to work.

How would one go about debugging the issue with the network? Just wondering when this happens to a client and they are unable to connect to another network.

**Comment by bric-stripe** [comment]
Unfortunately there's not much info provided back from the network request to help with debugging so usually some manual network investigation work is needed. For what it's worth this is the first time I'm hearing of an intermittent issue like this where all the sudden local traffic seems to just stall out and then start working again after a bit. Have you seen this on more than 1 network so far? The most common issue we see is with an IPS's DNS provider not supporting local IP addresses. That's what the primary focus of the previously mentioned support doc covers. With that situation it's at least a stable issue and usually solved by overriding with a public DNS provider.

**Comment by auctifera-josed** [comment]
So far only 1 network has presented this issue, changing the DNS provider did not help with the issue. We'll try to do some more network debugging and get back to you with more information if possible.

**Comment by bric-stripe** [comment]
Hi, cleaning up old issues. There aren't any known issues related to connecting aside from the DNS issue. Please re-open if you have more info on this though.
