### ISSUE TITLE
Idempotency key

### ISSUE THREAD

**Issue by maxivanyknix** [stripe/stripe-terminal-ios#188]
There are no headers with the Idempotency key on iOS. Android handles it properly:
![image-20221122-165323](https://user-images.githubusercontent.com/95284918/203587385-1a651731-24ab-4093-b67b-1510e6560d3f.png)

## iOS version
16.0

## SDK version
2.13.0

**Comment by bric-stripe** [comment]
Hi, is there an underlying issue you're hitting? Both SDKs rely on the server side payment intent state machine and should be handling retries correctly but if you're running in to a bug that you believe is caused by the lack of the idempotency key header from the clients happy to dig in to that.

fwiw from what I can tell neither platform uses the header today but the dashboard will list a key.

screenshot from iOS: 

<img width="200" alt="Screen Shot 2022-12-06 at 13 13 18" src="https://user-images.githubusercontent.com/62762265/206024830-7917e7b7-e440-412e-a87f-6b9b761f0e82.png">

**Comment by maxivanyknix** [comment]
Thank you for your response. We will implement this with server-side so thank you:slightly_smiling_face:
