### ISSUE TITLE
`PaymentIntentParameters` missing statement descriptor suffix option.

### ISSUE THREAD

**Issue by jacobmoncur** [stripe/stripe-terminal-ios#197]
## Summary
We need to be able to use the dynamic statement descriptor suffix so we end up with a statement descriptor formatted [like the following:](https://stripe.com/docs/account/statement-descriptors#dynamic) 
`<prefix>* <suffix>` 

The Terminal SDK does not have a parameter to set the statement descriptor suffix on payment intent creation, it only allows a static statement descriptor. 

Is this something you can add? 

If not, is it possible to include the asterisk `*` in the static statement descriptor to mimic the dynamic statement descriptor behavior [even though it is a disallowed character?](https://stripe.com/docs/account/statement-descriptors#requirements)

## Code to reproduce
See docs: 
https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPPaymentIntentParameters.html#/c:objc(cs)SCPPaymentIntentParameters(py)statementDescriptor
https://stripe.com/docs/account/statement-descriptors#dynamic
https://stripe.com/docs/account/statement-descriptors#requirements

## iOS version
N/A

## Installation method
N/A

## SDK version
N/A

## Other information
N/A

**Comment by bric-stripe** [comment]
Hi, I'm looking in to adding this for our next release, but that won't be until end of January. To immediately unblock you can switch to creating the PaymentIntent via the API instead of the SDK. Then to use that with Terminal you'll need to use the `retrievePaymentIntent` method to get that fetched as an `SCPPaymentIntent` the SDK will use. I realize that's not ideal since it requires another network request but it's the best option if you need this ASAP.

**Comment by bric-stripe** [comment]
sorry for delay in closing this out, these got added in 2.17.0 https://github.com/stripe/stripe-terminal-ios/blob/master/CHANGELOG.md#2170-2023-01-30
