### ISSUE TITLE
DiscoveryDelegate:didUpdateDiscoveredReaders called twice

### ISSUE THREAD

**Issue by troypayne** [stripe/stripe-terminal-ios#23]
This is being called twice for me. Once without hardwareInfo, deviceSoftwareVersion, and batteryLevel then again with all of this. Is this intentional? If not, can it just be returned once with all information?

**Comment by bg-stripe** [comment]
Hi Troy,

Yes, this is expected behavior when you use the Bluetooth proximity
discovery method. Under the hood, the SDK first discovers the reader via a
BT scan, and calls didUpdateDiscoveredReaders the first time. To get
metadata like batteryLevel, the SDK needs to connect to the BT device,
after we call didUpdateDiscoveredReaders a second time. Your app should
always expect that there may be multiple calls to
didUpdateDiscoveredReaders.

Hope that makes sense!

Ben

**Comment by troypayne** [comment]
Why not break these into two separate delegates?

**Comment by bg-stripe** [comment]
We'll keep that feedback in mind! For now, we prefer support multiple discovery methods using a consistent API. The `bluetoothScan` returns a list of readers that can be updated as the bluetooth scan results change, so `didUpdateDiscoveredReaders` will be called multiple times.

Keep the feedback coming as you think of it! It's always very appreciated, and really valuable as we get closer to v1.0.

**Comment by rdlabo** [comment]
> When discovering smart readers, the DiscoveryDelegate.didUpdateDiscoveredReaders method is only called once per call to discoverReaders. didUpdateDiscoveredReaders returns an empty list of readers if there are no registered readers or if there are no readers associated with the given location. If you make a subsequent discoverReaders call to refresh the list, you must first cancel the previous call with the Cancelable returned by discoverReaders.

https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=ios&reader-type=internet#discover-readers It says that it is only called once. Is there a need to update the documentation?
