### ISSUE TITLE
fetchConnectionToken is always called twice during connection

### ISSUE THREAD

**Issue by eugeneekus** [stripe/stripe-terminal-ios#231]
Hello! I've noticed the strange behaviour of the sdk. For some reason It calls fetchConnectionToken two times during connection. Is it expected behaviour, why so? 

Thanks for your help!

**Comment by billfinn-stripe** [comment]
Yes, it is expected. The SDK fetches once to activate/connect to the reader, and it fetches another connection token to fetch the reader's location.

I'm going to close this issue, since the behavior is expected, but feel free to leave additional feedback, particularly if fetching twice is causing problems for your integration.
