### ISSUE TITLE
Discovery Reader issue in real device 

### ISSUE THREAD

**Issue by Asfand-Hafeez** [stripe/stripe-terminal-ios#267]
When i try to test this project on iPhone XS i got this error 

Error Domain=com.stripe-terminal Code=2900 "Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid." UserInfo={com.stripe-terminal:ReaderMessage=Error usually caused by an entitlement issue, an invalid application bundle, a configuration issue, or a token issue., NSLocalizedDescription=Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid., com.stripe-terminal:Message=Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid

**Comment by bric-stripe** [comment]
Hi, there's some extra setup needed for Tap-to-Pay. Since the bundle id changes depending on who's running it the example app does't have the entitlement needed and has to be requested per app. More info in the docs for that https://stripe.com/docs/terminal/payments/setup-reader/tap-to-pay?platform=ios#entitlements-build-file

**Comment by Asfand-Hafeez** [comment]
Hey @bric-stripe  i am trying to integrate Tap to pay in ios app i have added all the necessary information 
entitlement, .plist permission  , Api Client but when i try to connect reader so got this error 

"Operation not permitted. Verify the app has the necessary entitlements and that the application bundle is valid."

i was checking your test project if there is something wrong at my side but this test project has same issue

**Comment by Asfand-Hafeez** [comment]
it has been long i discussed support team and live chat but nothing worked

**Comment by bric-stripe** [comment]
ah, gotcha. Sorry it's taking a bit but those support channels are probably the best bet. The example app failing with that error makes sense since it doesn't have the entitlement. This error from the Apple ProximityReader and is about the entitlement not being present. You went through the process of requesting the entitlement on the Apple developer portal and that's been granted there and then after that the entitlement file updated? Those are the only things I can think of to check.
