### ISSUE TITLE
`discoverReaders` calls completion with error when cancelled

### ISSUE THREAD

**Issue by r2-pro** [stripe/stripe-terminal-ios#272]
## Summary
Despite documentation stating:
> @note If `discoverReaders` is canceled, the completion block will be called
> with `nil` (rather than an `SCPErrorCanceled` error).

SDK calls completion block of `discoverReaders` with an error.

```
(lldb) print (error.self as NSError).userInfo
([String : Any]) 2 key/value pairs {
  [0] = {
    key = "com.stripe-terminal:Message"
    value = (object = 0x0000000283e1f720)
  }
  [1] = {
    key = "NSLocalizedDescription"
    value = (object = 0x0000000283e1f720)
  }
}
(lldb) po 0x0000000283e1f720
discoverReaders was canceled.
(lldb) po 0x0000000283e1f720
discoverReaders was canceled.
```

## iOS version
17.0.3

## Installation method
SPM

## SDK version
3.1.0

**Comment by bric-stripe** [comment]
@r2-pro sorry for the confusion here, and thanks for reporting. This was a change made in 3.0 and is called out in the [changelog](https://github.com/stripe/stripe-terminal-ios/blob/master/CHANGELOG.md#:~:text=Update%3A%20Canceling%20discoverReaders%20now%20completes%20with%20an%20SCPErrorCanceled%20error.%20Previously%20no%20error%20was%20provided%20when%20canceled.) 

> Update: Canceling discoverReaders now completes with an SCPErrorCanceled error. Previously no error was provided when canceled.

but we missed updating that note. I'll make sure this gets fixed up in the 3.3 release. But for now the behavior you're seeing in the expected behavior in 3.x SDKs.

fwiw this was for consistency with other commands that report the cancelled error as well as consistency with the Android SDK.
