### ISSUE TITLE
appstore connect permissions issue with tap to connect.

### ISSUE THREAD

**Issue by Fahad-pnw** [stripe/stripe-terminal-ios#295]
i have sent them demo video of the tap to pay functionality and explained to them that stripe sdk requires BLE functionality to be enabled. Although, for just tap to pay we do not really need bluetooth, what i can do to fix this?
--

Guideline 2.5.4 - Performance - Software Requirements

The app declares support for bluetooth-central in the UIBackgroundModes key in your Info.plist but we are unable to locate any Bluetooth Low Energy functionality. The Bluetooth Background modes are for apps that communicate to other devices using Bluetooth Low Energy and the Core Bluetooth framework.

Next Steps

If the app has a feature that requires Bluetooth functionality, reply to this message and let us know how to locate this feature. If the app does not have a feature that requires Bluetooth functionality, it would be appropriate to remove the bluetooth values from the UIBackgroundModes key.

---

**Comment by bric-stripe** [comment]
Hi, you should be able to remove `bluetooth-central` from the `UIBackgroundModes` without issue. The SDK only requires that `NSBluetoothAlwaysUsageDescription` is filled in (the auto app store validation requires this since it sees the SDK will have Core Bluetooth API usage) but the background mode is not required and the app should function without it if only using Tap to Pay.

**Comment by bric-stripe** [comment]
Closing this out as that should fix the issue but reopen if not.
