### ISSUE TITLE
stuck on 'An unexpected SDK error occurred'

### ISSUE THREAD

**Issue by r-grabowski** [stripe/stripe-terminal-ios#93]
When you turn off Bluetooth the connection process at the appropriate time SDK stuck and you can not connect again with 5000 error. 

## steps
1. Discover readers
2. Connect to reader
3. Turn off Bluetooth during the connection phase
4. `connectReader` throw error (example app just stuck in connecting state) : 

`Error Domain=com.stripe-terminal Code=2320 "Bluetooth is disabled on this iOS device. Enable bluetooth in Settings > Bluetooth." UserInfo={NSLocalizedDescription=Bluetooth is disabled on this iOS device. Enable bluetooth in Settings > Bluetooth., com.stripe-terminal:Message=Bluetooth is disabled on this iOS device. Enable bluetooth in Settings > Bluetooth.}`

5. Repeat again from #1
6. Got error:

`Error Domain=com.stripe-terminal Code=5000 "An unexpected SDK error occurred." UserInfo={com.stripe-terminal:ReaderMessage=ErrorType_IllegalStateException: Can only connect one BT device., NSLocalizedDescription=An unexpected SDK error occurred., com.stripe-terminal:Message=An unexpected SDK error occurred.}`

7. Additional when I'm trying to call `disconnectReader` it throw an error `Could not execute disconnectReader because the SDK is busy with another command: discoverReaders.`

## Code to reproduce
[video](https://youtu.be/xN8D974xAx4)

## iOS version
14.3

## SDK version
pod 'StripeTerminal', '1.4.0'

## Other information
device: Chipper™ 2X BT

**Comment by bric-stripe** [comment]
thanks for the detailed repro steps 👍 confirming we've been able to reproduce and the next release will address a couple things here:

1. when this happens, the connect will timeout and fail even if you don't re-enable BT (instead of hanging for as long as it does until BT is reenabled)
2. There's also an issue in the example app where it will show the connect error and then the discover view is still visible but attempts to connect will fail with an error about not being in the discovering state. It isn't fully cleaning up when the discover also fails. It should dismiss the discover VC too.

**Comment by bric-stripe** [comment]
@r-grabowski, thanks again for the detailed report. We’ve released version 2.0.0 of the Terminal iOS SDK which includes a fix for this issue and now reliably fails the connect call either with a timeout after ~4s or with a quick failure (depending on when the BT disabling happens in the connect cycle).
